version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo $FTP_HOST
      - run: echo $FTP_USERNAME
      - run: echo $FTP_PASSWORD
      - run: npm install
      - run: npx gatsby build
      - run: node .circleci/deploy.js
      - run: echo "WE'RE ONLINE"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
